### ISSUE TITLE
Support for Linter v2

### ISSUE THREAD

**Issue by ghost** [spockNinja/linter-scspell#6]
It seems this package doesn't support v2 and officially isn't working, 
@spockNinja please consider updating code or responding to this issue

**Comment by spockNinja** [comment]
Hi, @k1-hedayati. Thanks for creating an issue. I had an older version of scspell installed, so I did not notice the problem. It appears that since the time I wrote this plugin and now, scspell is now returning code `1` from the process when errors are found, and is sending output to `stderr` when using the `--report-only` flag. I will update the package soon!
